# The Site Configuration
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ko-KR

# Change to your timezone
timezone: Asia/Seoul

# jekyll-seo-tag settings
title: "FlameHeart 개발 공부"
tagline: "Autodesk Platform Service, Python, AI를 활용한 데이터 엔지니어링"
description: "불꽃심장의 기술 학습 및 트러블 슈팅 기록 공간입니다. 기술적 글쓰기를 위한 미니멀하고 반응형인 지킬 테마입니다."

# Fill in the protocol & hostname for your site.
url: "https://o-Fireheart-o.github.io"

github:
  username: "o-Fireheart-o"

social:
  name: "FlameHeart"
  email: "noa000694@gmail.com"
  links:
    - https://github.com/o-Fireheart-o

# ------------ 이후 설정들은 건드리지 않아도 됩니다 ------------------
baseurl: ""
paginate: 10

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
